c---------------------------------------------------------------------
c FILE CONTROL.INC 
c---------------------------------------------------------------------
        common /CONTROL/ setdegoff,stdhamoff,setbkq,setvkq,setxr,setakq,
     *                   setwx,setres,setself,setfit,setfirst,setprint,
     *                   setoverall,setpardis,setnowarnings,setquick,
     *                   setmonte
        integer setdegoff,stdhamoff,setbkq,setvkq,setxr,setakq,setwx
        integer setres,setself,setfit,setfirst,setprint,setoverall
        integer setpardis,setnowarnings,setquick,setmonte
c---------------------------------------------------------------------
