!--------------------------------------------------------------------------
! FILE FORMFACTOR.INC
!--------------------------------------------------------------------------
! define the arrays which are needed for the calculation of the formfactor
!--------------------------------------------------------------------------
!     define space for the calculation of the formfactor
      common /FORMFAKTOR/ st1,req(18),ref(266),feq(35),fef(35),nnn
      integer nnn
      real    st1,req,ref,feq,fef
!--------------------------------------------------------------------------
