!-----------------------------------------------------------------------
! INSTRUMENT.INC
!-----------------------------------------------------------------------
      common /INSTRU/ lmc_het, lcs_het, lsd_het, lsd_het_h,
     *                lmc_mari,lcs_mari,lsd_mari

      real*8          lmc_het, lcs_het, lsd_het, lsd_het_h
      real*8          lmc_mari,lcs_mari,lsd_mari
!-----------------------------------------------------------------------
