c-------------------------------------------------------------------- 
c  FILE XR.INC
c-------------------------------------------------------------------- 
        common /VKQXR/ fixold(MAX_PAR),pminold(MAX_PAR),pmaxold(MAX_PAR),
     *                 indvold(MAX_PAR),nindvold
        integer fixold,indvold,nindvold
        real*8  pminold,pmaxold
c--------------------------------------------------------------------        
